[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Ben Steadman <steadmanben1@gmail.com>"]
edition = "2018"

[features]
# Run slow tests
slowtests = []

[dependencies]
itertools = "0.9.0"
regex = "1.4.2"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "d16"
harness = false
